import { Injectable, OnModuleInit } from '@nestjs/common';
import { InjectModel } from '@nestjs/mongoose';
import { Model } from 'mongoose';
import {
  MarketplaceItem,
  MarketplaceItemDocument,
} from './schemas/marketplace-item.schema';
import { CreateItemDto } from './dto/create-item.dto';

interface FindAllQuery {
  type?: string;      // comma-separated backend types e.g. 'llm,multimodal'
  provider?: string;  // comma-separated provider names
  minRating?: number;
  maxPrice?: number;
  search?: string;
  tier?: string;      // 'free' | 'paid'
}

@Injectable()
export class MarketplaceService implements OnModuleInit {
  constructor(
    @InjectModel(MarketplaceItem.name)
    private itemModel: Model<MarketplaceItemDocument>,
  ) {}

  async onModuleInit() {
    await this.seed();
  }

  async findAll(query: FindAllQuery = {}) {
    const filter: any = {};

    if (query.type) {
      const types = query.type.split(',').map((t) => t.trim()).filter(Boolean);
      filter.type = types.length === 1 ? types[0] : { $in: types };
    }

    if (query.provider) {
      const providers = query.provider.split(',').map((p) => p.trim()).filter(Boolean);
      if (providers.length === 1) {
        filter.provider = { $regex: providers[0], $options: 'i' };
      } else {
        filter.$or = providers.map((p) => ({ provider: { $regex: p, $options: 'i' } }));
      }
    }

    if (query.tier) {
      filter['pricing.tier'] = query.tier;
    }

    if (query.minRating !== undefined) {
      filter.rating = { $gte: Number(query.minRating) };
    }

    if (query.maxPrice !== undefined) {
      filter['pricing.inputPer1M'] = { $lte: Number(query.maxPrice) };
    }

    if (query.search) {
      filter.$or = [
        { name: { $regex: query.search, $options: 'i' } },
        { description: { $regex: query.search, $options: 'i' } },
        { provider: { $regex: query.search, $options: 'i' } },
        { tags: { $in: [new RegExp(query.search, 'i')] } },
      ];
    }

    return this.itemModel.find(filter).sort({ featured: -1, rating: -1 }).lean();
  }

  async findOne(id: string) {
    return this.itemModel.findById(id).lean();
  }

  async create(dto: CreateItemDto) {
    const item = await this.itemModel.create(dto);
    return item.toObject();
  }

  async purchase(userId: string, itemId: string) {
    // Record purchase - simplified implementation
    return {
      success: true,
      message: 'Purchase recorded successfully',
      userId,
      itemId,
      purchasedAt: new Date().toISOString(),
    };
  }

  async seed() {
    const count = await this.itemModel.countDocuments();
    if (count > 0) {
      return { message: 'Marketplace already seeded', count };
    }

    const items: CreateItemDto[] = [
      // OpenAI Models
      {
        name: 'GPT-4o',
        provider: 'OpenAI',
        description: 'Most capable multimodal model for text, vision, and reasoning tasks. Optimized for speed and efficiency.',
        tags: ['reasoning', 'vision', 'multimodal', 'fast'],
        type: 'llm',
        badge: 'hot',
        pricing: { inputPer1M: 5, outputPer1M: 15, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.9,
        reviewCount: 4520,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'GPT-4o mini',
        provider: 'OpenAI',
        description: 'Affordable, intelligent small model for fast, lightweight tasks. Best for high-volume applications.',
        tags: ['fast', 'affordable', 'lightweight'],
        type: 'llm',
        badge: 'hot',
        pricing: { inputPer1M: 0.15, outputPer1M: 0.6, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.7,
        reviewCount: 3210,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'GPT-4 Turbo',
        provider: 'OpenAI',
        description: 'Enhanced GPT-4 model with improved instruction following, JSON mode, and a 128K context window.',
        tags: ['reasoning', 'instruction-following', 'json-mode'],
        type: 'llm',
        pricing: { inputPer1M: 10, outputPer1M: 30, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.8,
        reviewCount: 2850,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'GPT-3.5 Turbo',
        provider: 'OpenAI',
        description: 'Fast, inexpensive model for simple tasks. Good balance of capability and cost.',
        tags: ['fast', 'affordable', 'classic'],
        type: 'llm',
        pricing: { inputPer1M: 0.5, outputPer1M: 1.5, tier: 'paid' },
        contextWindow: 16385,
        rating: 4.5,
        reviewCount: 8900,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'o1',
        provider: 'OpenAI',
        description: 'Advanced reasoning model designed to solve complex problems in science, math, and coding.',
        tags: ['reasoning', 'math', 'science', 'code'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 15, outputPer1M: 60, tier: 'paid' },
        contextWindow: 200000,
        rating: 4.9,
        reviewCount: 1890,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'o1-mini',
        provider: 'OpenAI',
        description: 'Smaller, faster, and 80% cheaper than o1 while still powerful for coding, math, and science.',
        tags: ['reasoning', 'math', 'code', 'affordable'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 3, outputPer1M: 12, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.7,
        reviewCount: 1450,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'DALL-E 3',
        provider: 'OpenAI',
        description: 'State-of-the-art image generation model. Creates highly accurate images from text descriptions.',
        tags: ['image-generation', 'creative', 'art'],
        type: 'image',
        badge: 'hot',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'paid' },
        contextWindow: 0,
        rating: 4.8,
        reviewCount: 3200,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'Whisper',
        provider: 'OpenAI',
        description: 'General-purpose speech recognition model. Transcription and translation across 99 languages.',
        tags: ['speech-to-text', 'transcription', 'multilingual'],
        type: 'audio',
        pricing: { inputPer1M: 0.006, outputPer1M: 0, tier: 'paid' },
        contextWindow: 0,
        rating: 4.7,
        reviewCount: 2100,
        license: 'open-weights',
        featured: false,
      },
      {
        name: 'text-embedding-3-large',
        provider: 'OpenAI',
        description: 'Most capable embedding model for semantic search, text similarity, and RAG applications.',
        tags: ['embeddings', 'semantic-search', 'rag'],
        type: 'embedding',
        pricing: { inputPer1M: 0.13, outputPer1M: 0, tier: 'paid' },
        contextWindow: 8191,
        rating: 4.8,
        reviewCount: 1750,
        license: 'proprietary',
        featured: false,
      },
      // Anthropic Models
      {
        name: 'Claude 3.5 Sonnet',
        provider: 'Anthropic',
        description: 'Most intelligent Claude model to date. Excels at complex tasks, coding, and visual analysis.',
        tags: ['reasoning', 'coding', 'vision', 'analysis'],
        type: 'llm',
        badge: 'hot',
        pricing: { inputPer1M: 3, outputPer1M: 15, tier: 'paid' },
        contextWindow: 200000,
        rating: 4.9,
        reviewCount: 3870,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'Claude 3.5 Haiku',
        provider: 'Anthropic',
        description: 'Fastest and most compact Claude model. Ideal for near-instant responsiveness at scale.',
        tags: ['fast', 'affordable', 'compact'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 0.8, outputPer1M: 4, tier: 'paid' },
        contextWindow: 200000,
        rating: 4.7,
        reviewCount: 2150,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'Claude 3 Opus',
        provider: 'Anthropic',
        description: 'Powerful model for complex analysis, research, and long document understanding.',
        tags: ['reasoning', 'analysis', 'research', 'long-context'],
        type: 'llm',
        pricing: { inputPer1M: 15, outputPer1M: 75, tier: 'paid' },
        contextWindow: 200000,
        rating: 4.8,
        reviewCount: 2640,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'Claude 3 Haiku',
        provider: 'Anthropic',
        description: 'Near-instant responsiveness at cost-effective pricing. Great for customer interactions.',
        tags: ['fast', 'affordable', 'customer-service'],
        type: 'llm',
        pricing: { inputPer1M: 0.25, outputPer1M: 1.25, tier: 'paid' },
        contextWindow: 200000,
        rating: 4.6,
        reviewCount: 1980,
        license: 'proprietary',
        featured: false,
      },
      // Google Models
      {
        name: 'Gemini 1.5 Pro',
        provider: 'Google',
        description: 'Mid-size multimodal model with 2M token context window. Handles long documents, audio, and video.',
        tags: ['multimodal', 'long-context', 'video', 'audio'],
        type: 'multimodal',
        badge: 'hot',
        pricing: { inputPer1M: 3.5, outputPer1M: 10.5, tier: 'paid' },
        contextWindow: 2000000,
        rating: 4.8,
        reviewCount: 2980,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'Gemini 1.5 Flash',
        provider: 'Google',
        description: 'Fast, versatile multimodal model optimized for diverse tasks at scale with low latency.',
        tags: ['fast', 'multimodal', 'affordable', 'long-context'],
        type: 'multimodal',
        pricing: { inputPer1M: 0.075, outputPer1M: 0.3, tier: 'paid' },
        contextWindow: 1000000,
        rating: 4.6,
        reviewCount: 2340,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'Gemini 1.5 Flash-8B',
        provider: 'Google',
        description: 'Small model designed for lower intelligence tasks. High volume, low intelligence at lowest cost.',
        tags: ['lightweight', 'affordable', 'high-volume'],
        type: 'llm',
        pricing: { inputPer1M: 0.0375, outputPer1M: 0.15, tier: 'paid' },
        contextWindow: 1000000,
        rating: 4.4,
        reviewCount: 1560,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'Gemini 2.0 Flash',
        provider: 'Google',
        description: 'Next-gen model with superior speed and performance. Multimodal live API with native image generation.',
        tags: ['multimodal', 'real-time', 'image-generation', 'fast'],
        type: 'multimodal',
        badge: 'new',
        pricing: { inputPer1M: 0.1, outputPer1M: 0.4, tier: 'paid' },
        contextWindow: 1000000,
        rating: 4.8,
        reviewCount: 1120,
        license: 'proprietary',
        featured: true,
      },
      // Meta Models
      {
        name: 'Llama 3.3 70B',
        provider: 'Meta',
        description: 'Most capable open-source LLM. Excellent performance on reasoning, coding, and instruction following.',
        tags: ['open-source', 'reasoning', 'coding', 'instruction-following'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 128000,
        rating: 4.8,
        reviewCount: 5670,
        license: 'Llama 3 Community License',
        featured: true,
      },
      {
        name: 'Llama 3.2 90B Vision',
        provider: 'Meta',
        description: 'Largest Llama vision model. High-resolution image understanding and visual reasoning.',
        tags: ['vision', 'multimodal', 'open-source', 'image-understanding'],
        type: 'multimodal',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 128000,
        rating: 4.7,
        reviewCount: 1890,
        license: 'Llama 3 Community License',
        featured: false,
      },
      {
        name: 'Llama 3.2 11B Vision',
        provider: 'Meta',
        description: 'Mid-size vision model for image reasoning and visual question answering.',
        tags: ['vision', 'multimodal', 'open-source', 'efficient'],
        type: 'multimodal',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 128000,
        rating: 4.6,
        reviewCount: 1450,
        license: 'Llama 3 Community License',
        featured: false,
      },
      {
        name: 'Llama 3.2 3B',
        provider: 'Meta',
        description: 'Lightweight, efficient model for on-device and edge AI applications.',
        tags: ['edge', 'efficient', 'open-source', 'on-device'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 128000,
        rating: 4.5,
        reviewCount: 2100,
        license: 'Llama 3 Community License',
        featured: false,
      },
      {
        name: 'Llama 3.1 405B',
        provider: 'Meta',
        description: 'Largest open-source model. Matches GPT-4 performance on many benchmarks.',
        tags: ['open-source', 'reasoning', 'frontier', 'large'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 131072,
        rating: 4.8,
        reviewCount: 3200,
        license: 'Llama 3.1 Community License',
        featured: true,
      },
      // Mistral Models
      {
        name: 'Mistral Large 2',
        provider: 'Mistral AI',
        description: 'Top-tier reasoning for high-complexity tasks. Trained for coding and reasoning with 128K context.',
        tags: ['reasoning', 'coding', 'multilingual'],
        type: 'llm',
        pricing: { inputPer1M: 2, outputPer1M: 6, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.7,
        reviewCount: 1980,
        license: 'Mistral AI Research License',
        featured: false,
      },
      {
        name: 'Mistral Small 3',
        provider: 'Mistral AI',
        description: 'SOTA small model with best performance per dollar. Apache 2.0 license for commercial use.',
        tags: ['efficient', 'affordable', 'open-source'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 32000,
        rating: 4.5,
        reviewCount: 1340,
        license: 'Apache 2.0',
        featured: false,
      },
      {
        name: 'Mixtral 8x7B',
        provider: 'Mistral AI',
        description: 'Sparse mixture of experts model. Outperforms Llama 2 70B with 6x faster inference.',
        tags: ['mixture-of-experts', 'fast', 'open-source'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 32768,
        rating: 4.6,
        reviewCount: 2560,
        license: 'Apache 2.0',
        featured: false,
      },
      {
        name: 'Codestral',
        provider: 'Mistral AI',
        description: 'State-of-the-art Mistral model for code generation, completion and comments across 80+ languages.',
        tags: ['code', 'completion', 'programming', 'multilingual-code'],
        type: 'code',
        pricing: { inputPer1M: 0.2, outputPer1M: 0.6, tier: 'paid' },
        contextWindow: 32768,
        rating: 4.7,
        reviewCount: 1780,
        license: 'Mistral AI Non-Production License',
        featured: false,
      },
      // Cohere Models
      {
        name: 'Command R+',
        provider: 'Cohere',
        description: 'Powerful language model optimized for RAG and tool use. Enterprise-grade with 128K context.',
        tags: ['rag', 'tool-use', 'enterprise', 'search'],
        type: 'llm',
        pricing: { inputPer1M: 2.5, outputPer1M: 10, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.6,
        reviewCount: 1230,
        license: 'CC-BY-NC',
        featured: false,
      },
      {
        name: 'Command R',
        provider: 'Cohere',
        description: 'Scalable LLM for business. Optimized for conversational interaction and long-context tasks.',
        tags: ['business', 'conversational', 'long-context'],
        type: 'llm',
        pricing: { inputPer1M: 0.15, outputPer1M: 0.6, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.5,
        reviewCount: 980,
        license: 'CC-BY-NC',
        featured: false,
      },
      {
        name: 'Embed v3',
        provider: 'Cohere',
        description: 'Industry-leading embedding model. Best-in-class for semantic search and multilingual retrieval.',
        tags: ['embeddings', 'semantic-search', 'multilingual', 'rag'],
        type: 'embedding',
        pricing: { inputPer1M: 0.1, outputPer1M: 0, tier: 'paid' },
        contextWindow: 512,
        rating: 4.7,
        reviewCount: 1450,
        license: 'proprietary',
        featured: false,
      },
      // AI21 Models
      {
        name: 'Jamba 1.5 Large',
        provider: 'AI21 Labs',
        description: 'World\'s first production-grade Mamba-based model. 256K context with SSM architecture.',
        tags: ['ssm', 'long-context', 'efficient', 'mamba'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 2, outputPer1M: 8, tier: 'paid' },
        contextWindow: 256000,
        rating: 4.5,
        reviewCount: 780,
        license: 'Jamba Open Model License',
        featured: false,
      },
      // Stability AI
      {
        name: 'Stable Diffusion 3.5 Large',
        provider: 'Stability AI',
        description: 'Most powerful Stable Diffusion model. High quality, photorealistic image generation with text.',
        tags: ['image-generation', 'photorealistic', 'open-source'],
        type: 'image',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 0,
        rating: 4.7,
        reviewCount: 4560,
        license: 'Stability AI Community License',
        featured: true,
      },
      {
        name: 'Stable Diffusion XL',
        provider: 'Stability AI',
        description: 'Enhanced image synthesis model with better composition and face generation.',
        tags: ['image-generation', 'art', 'open-source'],
        type: 'image',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 0,
        rating: 4.6,
        reviewCount: 6780,
        license: 'CreativeML Open RAIL+M',
        featured: false,
      },
      // Black Forest Labs
      {
        name: 'FLUX.1 [pro]',
        provider: 'Black Forest Labs',
        description: 'State-of-the-art image generation. Exceptional prompt adherence, visual quality and diversity.',
        tags: ['image-generation', 'photorealistic', 'high-quality'],
        type: 'image',
        badge: 'hot',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'paid' },
        contextWindow: 0,
        rating: 4.9,
        reviewCount: 2340,
        license: 'proprietary',
        featured: true,
      },
      {
        name: 'FLUX.1 [schnell]',
        provider: 'Black Forest Labs',
        description: 'Fastest FLUX model. 4-step generation for local development and personal use.',
        tags: ['image-generation', 'fast', 'open-source'],
        type: 'image',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 0,
        rating: 4.7,
        reviewCount: 1890,
        license: 'Apache 2.0',
        featured: false,
      },
      // Deepseek
      {
        name: 'DeepSeek-V3',
        provider: 'DeepSeek',
        description: 'Powerful open-source model matching GPT-4 performance. Mixture-of-experts architecture.',
        tags: ['open-source', 'reasoning', 'moe', 'coding'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 131072,
        rating: 4.8,
        reviewCount: 2890,
        license: 'DeepSeek License',
        featured: true,
      },
      {
        name: 'DeepSeek-R1',
        provider: 'DeepSeek',
        description: 'Open-source reasoning model that matches o1 on benchmarks. Chain-of-thought reasoning.',
        tags: ['reasoning', 'math', 'open-source', 'chain-of-thought'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 131072,
        rating: 4.9,
        reviewCount: 3450,
        license: 'MIT',
        featured: true,
      },
      {
        name: 'DeepSeek Coder V2',
        provider: 'DeepSeek',
        description: 'Open-source code model matching GPT-4 Turbo in code generation. 338 programming languages.',
        tags: ['code', 'open-source', 'programming', 'moe'],
        type: 'code',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 128000,
        rating: 4.7,
        reviewCount: 2100,
        license: 'DeepSeek License',
        featured: false,
      },
      // Qwen Models
      {
        name: 'Qwen2.5 72B',
        provider: 'Alibaba',
        description: 'State-of-the-art open-source model. Excels at coding, math, and multilingual tasks.',
        tags: ['open-source', 'coding', 'math', 'multilingual'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 131072,
        rating: 4.7,
        reviewCount: 1980,
        license: 'Qwen License',
        featured: false,
      },
      {
        name: 'Qwen2.5-Coder 32B',
        provider: 'Alibaba',
        description: 'Best-in-class open-source code model. Matches GPT-4o on code generation benchmarks.',
        tags: ['code', 'open-source', 'programming', 'agentic-coding'],
        type: 'code',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 131072,
        rating: 4.8,
        reviewCount: 1670,
        license: 'Apache 2.0',
        featured: false,
      },
      {
        name: 'Qwen2-VL 72B',
        provider: 'Alibaba',
        description: 'Leading open-source vision model. Understands complex visual content and video.',
        tags: ['vision', 'multimodal', 'open-source', 'video'],
        type: 'multimodal',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 32768,
        rating: 4.7,
        reviewCount: 1120,
        license: 'Apache 2.0',
        featured: false,
      },
      // Microsoft Models
      {
        name: 'Phi-4',
        provider: 'Microsoft',
        description: 'Small but powerful model for reasoning. Outperforms much larger models on STEM reasoning.',
        tags: ['reasoning', 'math', 'stem', 'efficient'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 16384,
        rating: 4.6,
        reviewCount: 980,
        license: 'MIT',
        featured: false,
      },
      {
        name: 'Phi-3.5 MoE',
        provider: 'Microsoft',
        description: 'Mixture of experts model with strong multilingual capabilities and long context support.',
        tags: ['moe', 'multilingual', 'efficient', 'open-source'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 131072,
        rating: 4.5,
        reviewCount: 870,
        license: 'MIT',
        featured: false,
      },
      // Databricks
      {
        name: 'DBRX',
        provider: 'Databricks',
        description: 'Open, general-purpose LLM from Databricks. Best open-source model for instruction following.',
        tags: ['open-source', 'moe', 'instruction-following', 'enterprise'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 32768,
        rating: 4.5,
        reviewCount: 780,
        license: 'Databricks Open Model License',
        featured: false,
      },
      // xAI
      {
        name: 'Grok-2',
        provider: 'xAI',
        description: 'Advanced reasoning model with real-time web access. Excels at data analysis and coding.',
        tags: ['reasoning', 'real-time', 'coding', 'web-access'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 2, outputPer1M: 10, tier: 'paid' },
        contextWindow: 131072,
        rating: 4.7,
        reviewCount: 1230,
        license: 'proprietary',
        featured: false,
      },
      // Amazon
      {
        name: 'Nova Pro',
        provider: 'Amazon',
        description: 'Highly capable multimodal model for complex document analysis and content generation.',
        tags: ['multimodal', 'analysis', 'documents', 'enterprise'],
        type: 'multimodal',
        badge: 'new',
        pricing: { inputPer1M: 0.8, outputPer1M: 3.2, tier: 'paid' },
        contextWindow: 300000,
        rating: 4.6,
        reviewCount: 890,
        license: 'proprietary',
        featured: false,
      },
      {
        name: 'Nova Lite',
        provider: 'Amazon',
        description: 'Very low cost multimodal model for fast tasks with text, image, and video.',
        tags: ['multimodal', 'affordable', 'fast', 'video'],
        type: 'multimodal',
        pricing: { inputPer1M: 0.06, outputPer1M: 0.24, tier: 'paid' },
        contextWindow: 300000,
        rating: 4.4,
        reviewCount: 650,
        license: 'proprietary',
        featured: false,
      },
      // Perplexity
      {
        name: 'Sonar Pro',
        provider: 'Perplexity',
        description: 'Advanced search-augmented model with citations. Real-time web access for current information.',
        tags: ['search', 'real-time', 'citations', 'web-access'],
        type: 'llm',
        badge: 'new',
        pricing: { inputPer1M: 3, outputPer1M: 15, tier: 'paid' },
        contextWindow: 200000,
        rating: 4.7,
        reviewCount: 1450,
        license: 'proprietary',
        featured: false,
      },
      // Inflection AI
      {
        name: 'Inflection 3 Pi',
        provider: 'Inflection AI',
        description: 'Empathetic AI model optimized for conversational assistants and emotional intelligence.',
        tags: ['conversational', 'empathetic', 'assistant', 'emotional-intelligence'],
        type: 'llm',
        pricing: { inputPer1M: 2.5, outputPer1M: 10, tier: 'paid' },
        contextWindow: 8000,
        rating: 4.4,
        reviewCount: 560,
        license: 'proprietary',
        featured: false,
      },
      // Baidu
      {
        name: 'ERNIE 4.0',
        provider: 'Baidu',
        description: 'Enterprise-grade Chinese LLM with strong multilingual capabilities.',
        tags: ['chinese', 'multilingual', 'enterprise', 'knowledge-graph'],
        type: 'llm',
        pricing: { inputPer1M: 1.5, outputPer1M: 6, tier: 'paid' },
        contextWindow: 8192,
        rating: 4.3,
        reviewCount: 890,
        license: 'proprietary',
        featured: false,
      },
      // Writer
      {
        name: 'Palmyra X 004',
        provider: 'Writer',
        description: 'Enterprise-focused model with function calling and RAG capabilities for business workflows.',
        tags: ['enterprise', 'function-calling', 'rag', 'business'],
        type: 'llm',
        pricing: { inputPer1M: 5, outputPer1M: 20, tier: 'paid' },
        contextWindow: 128000,
        rating: 4.4,
        reviewCount: 450,
        license: 'proprietary',
        featured: false,
      },
      // Adept
      {
        name: 'Fuyu-8B',
        provider: 'Adept',
        description: 'Multimodal model specialized for digital agents, screen understanding and GUI automation.',
        tags: ['vision', 'gui', 'agents', 'screen-understanding'],
        type: 'multimodal',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 16384,
        rating: 4.3,
        reviewCount: 680,
        license: 'Apache 2.0',
        featured: false,
      },
      // Specialized Tools
      {
        name: 'Code Llama 70B',
        provider: 'Meta',
        description: 'Specialized coding model based on Llama 2. State-of-the-art for code generation tasks.',
        tags: ['code', 'open-source', 'programming', 'completion'],
        type: 'code',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 100000,
        rating: 4.6,
        reviewCount: 3450,
        license: 'Llama 2 Community License',
        featured: false,
      },
      {
        name: 'StarCoder2 15B',
        provider: 'Hugging Face',
        description: 'Next-gen code generation model trained on 600+ programming languages.',
        tags: ['code', 'open-source', 'multilingual-code', '600-languages'],
        type: 'code',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 16384,
        rating: 4.5,
        reviewCount: 1890,
        license: 'BigCode Open RAIL-M',
        featured: false,
      },
      {
        name: 'Falcon 180B',
        provider: 'TII UAE',
        description: 'Largest open-source model. Trained on 3.5 trillion tokens with exceptional generalization.',
        tags: ['open-source', 'large', 'generalization'],
        type: 'llm',
        badge: 'open',
        pricing: { inputPer1M: 0, outputPer1M: 0, tier: 'free' },
        contextWindow: 2048,
        rating: 4.4,
        reviewCount: 2100,
        license: 'Falcon License',
        featured: false,
      },
    ];

    await this.itemModel.insertMany(items);
    return { message: 'Marketplace seeded successfully', count: items.length };
  }
}
